import { useState, type FormEvent } from 'react'
import { Navigate, useLocation } from 'react-router-dom'
import { useAuth } from '../contexts/auth-context'

export default function Login() {
  const { session, isSessionLoading, signIn } = useAuth()
  const location = useLocation()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  if (!isSessionLoading && session) return <Navigate to={(location.state as { from?: string } | null)?.from ?? '/'} replace />
  async function handleSubmit(e: FormEvent) { e.preventDefault(); setError(null); if (!email || !password) { setError('Enter your email and password.'); return }; setIsSubmitting(true); const { error: signInError } = await signIn(email, password); setIsSubmitting(false); if (signInError) setError(signInError) }
  return <div className="min-h-screen bg-sidebar flex items-center justify-center px-5 py-8"><div className="w-full max-w-md"><div className="text-center mb-8"><div className="font-display font-semibold text-3xl tracking-tight text-white"><span className="text-market-300">JIUZE</span> POS</div><p className="text-sm text-sidebar-muted mt-2">Retail management, simplified.</p></div><form onSubmit={handleSubmit} className="rounded-2xl border border-sidebar-line bg-sidebar-card p-6 sm:p-7 shadow-2xl" noValidate><div className="mb-6"><p className="text-xs font-medium uppercase tracking-[0.16em] text-market-300">Welcome back</p><h1 className="font-display font-semibold text-2xl text-white mt-2">Sign in to your business</h1></div><div className="space-y-4"><div><label htmlFor="email" className="block text-xs font-medium text-sidebar-text mb-1.5">Email</label><input id="email" type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} disabled={isSubmitting} className="field bg-sidebar hover:border-sidebar-muted text-white placeholder:text-sidebar-muted border-sidebar-line" placeholder="you@business.co.ke" /></div><div><label htmlFor="password" className="block text-xs font-medium text-sidebar-text mb-1.5">Password</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} disabled={isSubmitting} className="field bg-sidebar hover:border-sidebar-muted text-white placeholder:text-sidebar-muted border-sidebar-line" placeholder="••••••••" /></div></div>{error && <p role="alert" className="mt-4 text-xs text-red-200 bg-brick-500/15 border border-brick-500/30 rounded-lg px-3 py-2.5 leading-relaxed">{error}</p>}<button type="submit" disabled={isSubmitting} className="mt-6 w-full rounded-lg bg-market-600 text-white text-sm font-semibold py-3 hover:bg-market-700 transition-colors disabled:opacity-60 disabled:cursor-not-allowed">{isSubmitting ? 'Signing in…' : 'Sign in'}</button></form><p className="text-center text-xs text-sidebar-muted mt-6">Secure business access · JIUZE POS</p></div></div>
}
