import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../contexts/auth-context'
import { listStockMovements, type StockMovement } from '../services/stockMovementService'

const labels: Record<StockMovement['type'], string> = { purchase: 'Purchase', adjustment: 'Adjustment', return: 'Return', damage: 'Damage' }
const moneyQuantity = (value: number) => Number.isInteger(value) ? String(value) : value.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')

function TypeIcon({ type }: { type: StockMovement['type'] }) {
  const path = type === 'damage' ? 'M12 3v18M5 8h14M5 16h14' : type === 'return' ? 'M5 12a7 7 0 1 0 2-5.1M5 5v5h5' : type === 'purchase' ? 'M12 5v14M5 12h14' : 'M6 12h12M12 6v12'
  return <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><path d={path} /></svg>
}

export default function StockMovements() {
  const { profile, role } = useAuth()
  const [movements, setMovements] = useState<StockMovement[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [search, setSearch] = useState('')
  const [typeFilter, setTypeFilter] = useState<'all' | StockMovement['type']>('all')

  const load = useCallback(async () => { if (!profile?.businessId || role !== 'owner') return; setLoading(true); setError(null); try { setMovements(await listStockMovements(profile.businessId)) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load stock history.') } finally { setLoading(false) } }, [profile?.businessId, role])
  useEffect(() => { void load() }, [load])

  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return movements.filter((movement) => { const matchesSearch = !query || movement.productName.toLowerCase().includes(query) || movement.sku.toLowerCase().includes(query) || (movement.reason ?? '').toLowerCase().includes(query); const matchesType = typeFilter === 'all' || movement.type === typeFilter; return matchesSearch && matchesType }) }, [movements, search, typeFilter])
  const additions = movements.filter((m) => m.quantity > 0).length
  const reductions = movements.filter((m) => m.quantity < 0).length
  const damages = movements.filter((m) => m.type === 'damage').length

  if (role !== 'owner') return <div className="min-h-screen bg-paper px-5 py-8 sm:px-6"><div className="max-w-6xl mx-auto"><header className="mb-8"><p className="text-xs font-medium uppercase tracking-[0.16em] text-market-600">Inventory</p><h1 className="font-display font-semibold text-3xl sm:text-4xl text-ink mt-2">Stock history</h1></header><div className="rounded-2xl border border-line bg-paper-raised p-10 text-center"><h2 className="font-display font-semibold text-xl text-ink">Access restricted</h2><p className="text-sm text-ink-muted mt-2">Stock history is available to business owners only.</p></div></div></div>

  return <div className="min-h-screen bg-paper px-5 py-6 sm:px-6 lg:px-8"><div className="max-w-[1500px] mx-auto">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between mb-7"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-market-600">Inventory control</p><h1 className="font-display font-semibold text-3xl sm:text-4xl tracking-tight text-ink mt-2">Stock history</h1><p className="text-sm text-ink-muted mt-2">Track every movement in and out of your inventory.</p></div><Link to="/products" className="inline-flex self-start rounded-lg bg-ink px-4 py-2.5 text-sm font-medium text-paper">Manage products</Link></header>
    {error && <div role="alert" className="mb-5 rounded-xl border border-brick-200 bg-brick-50 px-4 py-3 text-sm text-brick-700">{error}</div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 mb-5"><Stat label="Total movements" value={movements.length} detail="All recorded activity" /><Stat label="Stock additions" value={additions} detail="Positive movements" /><Stat label="Stock reductions" value={reductions} detail="Negative movements" /><Stat label="Damage records" value={damages} detail="Loss / damage activity" alert={damages > 0} /></section>
    <section className="rounded-2xl border border-line bg-paper-raised p-4 sm:p-5 mb-5"><div className="flex flex-col gap-3 lg:flex-row"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search product, SKU or reason..." aria-label="Search stock history" className="field flex-1" /><select value={typeFilter} onChange={(e) => setTypeFilter(e.target.value as typeof typeFilter)} aria-label="Filter movement type" className="field lg:w-52"><option value="all">All movement types</option><option value="purchase">Purchases</option><option value="adjustment">Adjustments</option><option value="return">Returns</option><option value="damage">Damage</option></select></div><div className="flex gap-2 overflow-x-auto pt-3 pb-1">{(['all','purchase','adjustment','return','damage'] as const).map((type) => <button key={type} type="button" onClick={() => setTypeFilter(type)} className={`shrink-0 rounded-full px-3.5 py-1.5 text-xs font-medium ${typeFilter === type ? 'bg-ink text-paper' : 'bg-paper border border-line text-ink-muted hover:text-ink'}`}>{type === 'all' ? 'All' : labels[type]}</button>)}</div></section>
    <section className="rounded-2xl border border-line bg-paper-raised overflow-hidden"><div className="px-5 py-5 border-b border-line flex items-center justify-between gap-4"><div><h2 className="font-display font-semibold text-xl text-ink">Inventory movements</h2><p className="text-xs text-ink-muted mt-1">Showing {filtered.length} of {movements.length} records</p></div><span className="rounded-full bg-paper px-3 py-1.5 text-xs font-mono text-ink-muted">Live record</span></div>
      {loading ? <div className="px-5 py-14 text-center text-sm text-ink-muted">Loading stock history…</div> : filtered.length === 0 ? <div className="px-5 py-14 text-center"><p className="text-sm font-medium text-ink">No movements found</p><p className="text-xs text-ink-muted mt-1">Try changing the search or filter.</p></div> : <><div className="hidden md:block overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-line text-left text-[11px] uppercase tracking-wide text-ink-muted"><th className="px-5 py-3">Date</th><th className="px-3 py-3">Product</th><th className="px-3 py-3">Movement</th><th className="px-3 py-3">Quantity</th><th className="px-3 py-3">Reason</th><th className="px-5 py-3">Created by</th></tr></thead><tbody className="divide-y divide-line">{filtered.map((movement) => <tr key={movement.id} className="hover:bg-paper"><td className="px-5 py-4 text-xs text-ink-muted whitespace-nowrap">{new Date(movement.createdAt).toLocaleString()}</td><td className="px-3 py-4"><p className="font-medium text-ink">{movement.productName}</p><p className="font-mono text-[11px] text-ink-muted mt-1">{movement.sku}</p></td><td className="px-3 py-4"><span className="inline-flex items-center gap-2 rounded-full bg-paper px-2.5 py-1 text-xs text-ink-muted"><TypeIcon type={movement.type} />{labels[movement.type]}</span></td><td className={`px-3 py-4 font-mono font-semibold ${movement.quantity > 0 ? 'text-market-700' : 'text-brick-600'}`}>{movement.quantity > 0 ? '+' : ''}{moneyQuantity(movement.quantity)}</td><td className="px-3 py-4 text-ink-muted max-w-xs truncate">{movement.reason ?? '—'}</td><td className="px-5 py-4 font-mono text-[11px] text-ink-muted">{movement.createdBy ? `${movement.createdBy.slice(0, 8)}…` : '—'}</td></tr>)}</tbody></table></div><div className="md:hidden divide-y divide-line">{filtered.map((movement) => <div key={movement.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-sm text-ink">{movement.productName}</p><p className="font-mono text-[11px] text-ink-muted mt-1">{movement.sku}</p></div><span className={`font-mono font-semibold text-sm ${movement.quantity > 0 ? 'text-market-700' : 'text-brick-600'}`}>{movement.quantity > 0 ? '+' : ''}{moneyQuantity(movement.quantity)}</span></div><div className="flex items-center justify-between gap-3 mt-3 text-xs text-ink-muted"><span className="inline-flex items-center gap-1.5"><TypeIcon type={movement.type} />{labels[movement.type]}</span><span>{new Date(movement.createdAt).toLocaleDateString()}</span></div>{movement.reason && <p className="text-xs text-ink-muted mt-2">{movement.reason}</p>}</div>)}</div></>}
    </section>
  </div></div>
}

function Stat({ label, value, detail, alert = false }: { label: string; value: number; detail: string; alert?: boolean }) { return <div className="rounded-2xl border border-line bg-paper-raised p-5"><p className="text-xs font-medium uppercase tracking-wide text-ink-muted">{label}</p><p className="font-display font-semibold text-2xl text-ink mt-3">{value}</p><p className={`text-xs mt-1 ${alert ? 'text-brick-600' : 'text-ink-muted'}`}>{detail}</p></div> }
